#!/bin/bash

# for tramp mode
export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock

# [ -t 0 ] is false inside pipelines
# if [ -z "${gui}" ]
if [ -t 0 ] && [ -z "${gui}" ]
then
	emacsclient -nw -a '' "${@}"
else
	emacsclient -c -a '' "${@}"
fi
