#!/usr/bin/env bash

set -e

mkdir --parents /tmp/emacsclient-pager
file="$(mktemp /tmp/emacsclient-pager/XXXXX.pager)"
cat >"${file}" </dev/stdin &
catpid=$!
emacsclient "${file}"
if ps --pid "${catpid}" > /dev/null; then
   kill --signal TERM --timeout 1000 KILL "${catpid}"
fi
rm "${file}"
